version: '3'
services: 
    nginx:
        image: nginx
        network_mode: "host"
        volumes:
          - ./nginx/default_local:/etc/nginx/conf.d/default.conf
        ports:
          - 80:80    
        