# Generated by Django 3.1.3 on 2020-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
