name: SSH Remote Commands

on:
  push:
    branches: [ master ]
jobs:

  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: | 
          cd /home/ubuntu/buserlab
          git fetch origin
          git checkout origin/master
          sh scripts/backend.sh
          
